[package]
name = "zxing-rs"
version = "0.1.0"
authors = ["higumachan <harekumo792154@gmail.com>"]
edition = "2018"

[build-dependencies]
glob = "0.3.0"
cc = "1.0.4"

[dependencies]
image = "0.21"
num = "*"